export const DOMAIN = "scene_presets";

export const DEFAULT_STYLES = {
    "--layout-invisible_-_visibility": "hidden ",
    "--fc-list-event-hover-bg-color": "#f5f5f5",
    "--fc-list-event-dot-width": "10px",
    "--fc-daygrid-event-dot-width": "8px",
    "--fc-now-indicator-color": "red",
    "--fc-today-bg-color": "rgba(255,220,40,.15)",
    "--fc-highlight-color": "rgba(188,232,241,.3)",
    "--fc-bg-event-opacity": "0.3",
    "--fc-bg-event-color": "#8fdf82",
    "--fc-non-business-color": "hsla(0,0%,84%,.3)",
    "--fc-event-resizer-dot-border-width": "1px",
    "--fc-event-resizer-dot-total-width": "8px",
    "--fc-event-resizer-thickness": "8px",
    "--fc-more-link-bg-color": "#d0d0d0",
    "--fc-event-selected-overlay-color": "rgba(0,0,0,.25)",
    "--fc-event-text-color": "#fff",
    "--fc-event-border-color": "#3788d8",
    "--fc-event-bg-color": "#3788d8",
    "--fc-button-active-border-color": "#151e27",
    "--fc-button-active-bg-color": "#1a252f",
    "--fc-button-hover-border-color": "#1a252f",
    "--fc-button-hover-bg-color": "#1e2b37",
    "--fc-button-border-color": "#2c3e50",
    "--fc-button-bg-color": "#2c3e50",
    "--fc-button-text-color": "#fff",
    "--fc-border-color": "#ddd",
    "--fc-neutral-text-color": "grey",
    "--fc-neutral-bg-color": "hsla(0,0%,82%,.3)",
    "--fc-page-bg-color": "#fff",
    "--fc-small-font-size": ".85em",
    "--paper-input-container-shared-input-style_-_line-height": "24px",
    "--paper-input-container-shared-input-style_-_font-weight": "400",
    "--paper-input-container-shared-input-style_-_font-size": "16px",
    "--paper-input-container-shared-input-style_-_-webkit-font-smoothing": "antialiased",
    "--paper-input-container-shared-input-style_-_font-family": "'Roboto', 'Noto', sans-serif",
    "--paper-input-container-shared-input-style_-_vertical-align": "bottom",
    "--paper-input-container-shared-input-style_-_text-align": "apply-shim-inherit",
    "--paper-input-container-shared-input-style_-_-webkit-appearance": "none",
    "--paper-input-container-shared-input-style_-_color": "#212121",
    "--paper-input-container-shared-input-style_-_border": "none",
    "--paper-input-container-shared-input-style_-_background": "transparent",
    "--paper-input-container-shared-input-style_-_max-width": "100%",
    "--paper-input-container-shared-input-style_-_width": "100%",
    "--paper-input-container-shared-input-style_-_margin": "0",
    "--paper-input-container-shared-input-style_-_padding": "0",
    "--paper-input-container-shared-input-style_-_box-shadow": "none",
    "--paper-input-container-shared-input-style_-_outline": "none",
    "--paper-input-container-shared-input-style_-_position": "relative",
    "--paper-font-code1_-_line-height": "20px",
    "--paper-font-code1_-_font-weight": "500",
    "--paper-font-code1_-_font-size": "14px",
    "--paper-font-code1_-_-webkit-font-smoothing": "antialiased",
    "--paper-font-code1_-_font-family": "'Roboto Mono', 'Consolas', 'Menlo', monospace",
    "--paper-font-code2_-_line-height": "20px",
    "--paper-font-code2_-_font-weight": "700",
    "--paper-font-code2_-_font-size": "14px",
    "--paper-font-code2_-_-webkit-font-smoothing": "antialiased",
    "--paper-font-code2_-_font-family": "'Roboto Mono', 'Consolas', 'Menlo', monospace",
    "--paper-font-button_-_text-transform": "uppercase",
    "--paper-font-button_-_line-height": "24px",
    "--paper-font-button_-_letter-spacing": "0.018em",
    "--paper-font-button_-_font-weight": "500",
    "--paper-font-button_-_font-size": "14px",
    "--paper-font-button_-_text-overflow": "ellipsis",
    "--paper-font-button_-_overflow": "hidden",
    "--paper-font-button_-_white-space": "nowrap",
    "--paper-font-button_-_-webkit-font-smoothing": "antialiased",
    "--paper-font-button_-_font-family": "'Roboto', 'Noto', sans-serif",
    "--paper-font-menu_-_line-height": "24px",
    "--paper-font-menu_-_font-weight": "500",
    "--paper-font-menu_-_font-size": "13px",
    "--paper-font-menu_-_text-overflow": "ellipsis",
    "--paper-font-menu_-_overflow": "hidden",
    "--paper-font-menu_-_white-space": "nowrap",
    "--paper-font-menu_-_-webkit-font-smoothing": "antialiased",
    "--paper-font-menu_-_font-family": "'Roboto', 'Noto', sans-serif",
    "--paper-font-caption_-_line-height": "20px",
    "--paper-font-caption_-_letter-spacing": "0.011em",
    "--paper-font-caption_-_font-weight": "400",
    "--paper-font-caption_-_font-size": "12px",
    "--paper-font-caption_-_text-overflow": "ellipsis",
    "--paper-font-caption_-_overflow": "hidden",
    "--paper-font-caption_-_white-space": "nowrap",
    "--paper-font-caption_-_-webkit-font-smoothing": "antialiased",
    "--paper-font-caption_-_font-family": "'Roboto', 'Noto', sans-serif",
    "--paper-font-body1_-_line-height": "20px",
    "--paper-font-body1_-_font-weight": "400",
    "--paper-font-body1_-_font-size": "14px",
    "--paper-font-body1_-_-webkit-font-smoothing": "antialiased",
    "--paper-font-body1_-_font-family": "'Roboto', 'Noto', sans-serif",
    "--paper-font-body2_-_line-height": "24px",
    "--paper-font-body2_-_font-weight": "500",
    "--paper-font-body2_-_font-size": "14px",
    "--paper-font-body2_-_-webkit-font-smoothing": "antialiased",
    "--paper-font-body2_-_font-family": "'Roboto', 'Noto', sans-serif",
    "--paper-font-subhead_-_line-height": "24px",
    "--paper-font-subhead_-_font-weight": "400",
    "--paper-font-subhead_-_font-size": "16px",
    "--paper-font-subhead_-_-webkit-font-smoothing": "antialiased",
    "--paper-font-subhead_-_font-family": "'Roboto', 'Noto', sans-serif",
    "--paper-font-title_-_line-height": "28px",
    "--paper-font-title_-_font-weight": "500",
    "--paper-font-title_-_font-size": "20px",
    "--paper-font-title_-_text-overflow": "ellipsis",
    "--paper-font-title_-_overflow": "hidden",
    "--paper-font-title_-_white-space": "nowrap",
    "--paper-font-title_-_-webkit-font-smoothing": "antialiased",
    "--paper-font-title_-_font-family": "'Roboto', 'Noto', sans-serif",
    "--paper-font-headline_-_line-height": "32px",
    "--paper-font-headline_-_letter-spacing": "-.012em",
    "--paper-font-headline_-_font-weight": "400",
    "--paper-font-headline_-_font-size": "24px",
    "--paper-font-headline_-_-webkit-font-smoothing": "antialiased",
    "--paper-font-headline_-_font-family": "'Roboto', 'Noto', sans-serif",
    "--paper-font-display1_-_line-height": "40px",
    "--paper-font-display1_-_letter-spacing": "-.01em",
    "--paper-font-display1_-_font-weight": "400",
    "--paper-font-display1_-_font-size": "34px",
    "--paper-font-display1_-_-webkit-font-smoothing": "antialiased",
    "--paper-font-display1_-_font-family": "'Roboto', 'Noto', sans-serif",
    "--paper-font-display2_-_line-height": "48px",
    "--paper-font-display2_-_letter-spacing": "-.018em",
    "--paper-font-display2_-_font-weight": "400",
    "--paper-font-display2_-_font-size": "45px",
    "--paper-font-display2_-_-webkit-font-smoothing": "antialiased",
    "--paper-font-display2_-_font-family": "'Roboto', 'Noto', sans-serif",
    "--paper-font-display3_-_line-height": "60px",
    "--paper-font-display3_-_letter-spacing": "-.026em",
    "--paper-font-display3_-_font-weight": "400",
    "--paper-font-display3_-_font-size": "56px",
    "--paper-font-display3_-_text-overflow": "ellipsis",
    "--paper-font-display3_-_overflow": "hidden",
    "--paper-font-display3_-_white-space": "nowrap",
    "--paper-font-display3_-_-webkit-font-smoothing": "antialiased",
    "--paper-font-display3_-_font-family": "'Roboto', 'Noto', sans-serif",
    "--paper-font-display4_-_line-height": "120px",
    "--paper-font-display4_-_letter-spacing": "-.044em",
    "--paper-font-display4_-_font-weight": "300",
    "--paper-font-display4_-_font-size": "112px",
    "--paper-font-display4_-_text-overflow": "ellipsis",
    "--paper-font-display4_-_overflow": "hidden",
    "--paper-font-display4_-_white-space": "nowrap",
    "--paper-font-display4_-_-webkit-font-smoothing": "antialiased",
    "--paper-font-display4_-_font-family": "'Roboto', 'Noto', sans-serif",
    "--paper-font-common-nowrap_-_text-overflow": "ellipsis",
    "--paper-font-common-nowrap_-_overflow": "hidden",
    "--paper-font-common-nowrap_-_white-space": "nowrap",
    "--paper-font-common-expensive-kerning_-_text-rendering": "optimizeLegibility",
    "--paper-font-common-code_-_-webkit-font-smoothing": "antialiased",
    "--paper-font-common-code_-_font-family": "'Roboto Mono', 'Consolas', 'Menlo', monospace",
    "--paper-font-common-base_-_-webkit-font-smoothing": "antialiased",
    "--paper-font-common-base_-_font-family": "'Roboto', 'Noto', sans-serif",
    "--layout-fixed-left_-_left": "0",
    "--layout-fixed-left_-_bottom": "0",
    "--layout-fixed-left_-_top": "0",
    "--layout-fixed-left_-_position": "fixed",
    "--layout-fixed-bottom_-_left": "0",
    "--layout-fixed-bottom_-_bottom": "0",
    "--layout-fixed-bottom_-_right": "0",
    "--layout-fixed-bottom_-_position": "fixed",
    "--layout-fixed-right_-_bottom": "0",
    "--layout-fixed-right_-_right": "0",
    "--layout-fixed-right_-_top": "0",
    "--layout-fixed-right_-_position": "fixed",
    "--layout-fixed-top_-_right": "0",
    "--layout-fixed-top_-_left": "0",
    "--layout-fixed-top_-_top": "0",
    "--layout-fixed-top_-_position": "fixed",
    "--layout-fullbleed_-_height": "100vh",
    "--layout-fullbleed_-_margin": "0",
    "--layout-scroll_-_overflow": "auto",
    "--layout-scroll_-_-webkit-overflow-scrolling": "touch",
    "--layout-fit_-_left": "0",
    "--layout-fit_-_bottom": "0",
    "--layout-fit_-_right": "0",
    "--layout-fit_-_top": "0",
    "--layout-fit_-_position": "absolute",
    "--layout-relative_-_position": "relative",
    "--layout-block_-_display": "block",
    "--layout-around-aligned_-_align-content": "space-around",
    "--layout-around-aligned_-_-webkit-align-content": "space-around",
    "--layout-around-aligned_-_-ms-align-content": "space-around",
    "--layout-around-aligned_-_-ms-flex-line-pack": "distribute",
    "--layout-between-aligned_-_align-content": "space-between",
    "--layout-between-aligned_-_-webkit-align-content": "space-between",
    "--layout-between-aligned_-_-ms-align-content": "space-between",
    "--layout-between-aligned_-_-ms-flex-line-pack": "justify",
    "--layout-center-aligned_-_align-content": "center",
    "--layout-center-aligned_-_-webkit-align-content": "center",
    "--layout-center-aligned_-_-ms-align-content": "center",
    "--layout-center-aligned_-_-ms-flex-line-pack": "center",
    "--layout-end-aligned_-_align-content": "flex-end",
    "--layout-end-aligned_-_-webkit-align-content": "flex-end",
    "--layout-end-aligned_-_-ms-align-content": "flex-end",
    "--layout-end-aligned_-_-ms-flex-line-pack": "end",
    "--layout-start-aligned_-_align-content": "flex-start",
    "--layout-start-aligned_-_-webkit-align-content": "flex-start",
    "--layout-start-aligned_-_-ms-align-content": "flex-start",
    "--layout-start-aligned_-_-ms-flex-line-pack": "start",
    "--layout-self-baseline_-_align-self": "baseline",
    "--layout-self-baseline_-_-webkit-align-self": "baseline",
    "--layout-self-baseline_-_-ms-align-self": "baseline",
    "--layout-self-stretch_-_align-self": "stretch",
    "--layout-self-stretch_-_-webkit-align-self": "stretch",
    "--layout-self-stretch_-_-ms-align-self": "stretch",
    "--layout-self-end_-_align-self": "flex-end",
    "--layout-self-end_-_-webkit-align-self": "flex-end",
    "--layout-self-end_-_-ms-align-self": "flex-end",
    "--layout-self-center_-_align-self": "center",
    "--layout-self-center_-_-webkit-align-self": "center",
    "--layout-self-center_-_-ms-align-self": "center",
    "--layout-self-start_-_align-self": "flex-start",
    "--layout-self-start_-_-webkit-align-self": "flex-start",
    "--layout-self-start_-_-ms-align-self": "flex-start",
    "--layout-center-center_-_justify-content": "center",
    "--layout-center-center_-_-webkit-justify-content": "center",
    "--layout-center-center_-_-ms-flex-pack": "center",
    "--layout-center-center_-_align-items": "center",
    "--layout-center-center_-_-webkit-align-items": "center",
    "--layout-center-center_-_-ms-flex-align": "center",
    "--layout-justified_-_justify-content": "space-between",
    "--layout-justified_-_-webkit-justify-content": "space-between",
    "--layout-justified_-_-ms-flex-pack": "justify",
    "--layout-around-justified_-_justify-content": "space-around",
    "--layout-around-justified_-_-webkit-justify-content": "space-around",
    "--layout-around-justified_-_-ms-flex-pack": "distribute",
    "--layout-end-justified_-_justify-content": "flex-end",
    "--layout-end-justified_-_-webkit-justify-content": "flex-end",
    "--layout-end-justified_-_-ms-flex-pack": "end",
    "--layout-center-justified_-_justify-content": "center",
    "--layout-center-justified_-_-webkit-justify-content": "center",
    "--layout-center-justified_-_-ms-flex-pack": "center",
    "--layout-start-justified_-_justify-content": "flex-start",
    "--layout-start-justified_-_-webkit-justify-content": "flex-start",
    "--layout-start-justified_-_-ms-flex-pack": "start",
    "--layout-baseline_-_align-items": "baseline",
    "--layout-baseline_-_-webkit-align-items": "baseline",
    "--layout-baseline_-_-ms-flex-align": "baseline",
    "--layout-end_-_align-items": "flex-end",
    "--layout-end_-_-webkit-align-items": "flex-end",
    "--layout-end_-_-ms-flex-align": "end",
    "--layout-center_-_align-items": "center",
    "--layout-center_-_-webkit-align-items": "center",
    "--layout-center_-_-ms-flex-align": "center",
    "--layout-start_-_align-items": "flex-start",
    "--layout-start_-_-webkit-align-items": "flex-start",
    "--layout-start_-_-ms-flex-align": "start",
    "--layout-flex-12_-_flex": "12",
    "--layout-flex-12_-_-webkit-flex": "12",
    "--layout-flex-12_-_-ms-flex": "12",
    "--layout-flex-11_-_flex": "11",
    "--layout-flex-11_-_-webkit-flex": "11",
    "--layout-flex-11_-_-ms-flex": "11",
    "--layout-flex-10_-_flex": "10",
    "--layout-flex-10_-_-webkit-flex": "10",
    "--layout-flex-10_-_-ms-flex": "10",
    "--layout-flex-9_-_flex": "9",
    "--layout-flex-9_-_-webkit-flex": "9",
    "--layout-flex-9_-_-ms-flex": "9",
    "--layout-flex-8_-_flex": "8",
    "--layout-flex-8_-_-webkit-flex": "8",
    "--layout-flex-8_-_-ms-flex": "8",
    "--layout-flex-7_-_flex": "7",
    "--layout-flex-7_-_-webkit-flex": "7",
    "--layout-flex-7_-_-ms-flex": "7",
    "--layout-flex-6_-_flex": "6",
    "--layout-flex-6_-_-webkit-flex": "6",
    "--layout-flex-6_-_-ms-flex": "6",
    "--layout-flex-5_-_flex": "5",
    "--layout-flex-5_-_-webkit-flex": "5",
    "--layout-flex-5_-_-ms-flex": "5",
    "--layout-flex-4_-_flex": "4",
    "--layout-flex-4_-_-webkit-flex": "4",
    "--layout-flex-4_-_-ms-flex": "4",
    "--layout-flex-3_-_flex": "3",
    "--layout-flex-3_-_-webkit-flex": "3",
    "--layout-flex-3_-_-ms-flex": "3",
    "--layout-flex-2_-_flex": "2",
    "--layout-flex-2_-_-webkit-flex": "2",
    "--layout-flex-2_-_-ms-flex": "2",
    "--layout-flex_-_flex-basis": "0.000000001px",
    "--layout-flex_-_-webkit-flex-basis": "0.000000001px",
    "--layout-flex_-_flex": "1",
    "--layout-flex_-_-webkit-flex": "1",
    "--layout-flex_-_-ms-flex": "1 1 0.000000001px",
    "--layout-flex-none_-_flex": "none",
    "--layout-flex-none_-_-webkit-flex": "none",
    "--layout-flex-none_-_-ms-flex": "none",
    "--layout-flex-auto_-_flex": "1 1 auto",
    "--layout-flex-auto_-_-webkit-flex": "1 1 auto",
    "--layout-flex-auto_-_-ms-flex": "1 1 auto",
    "--layout-wrap-reverse_-_flex-wrap": "wrap-reverse",
    "--layout-wrap-reverse_-_-webkit-flex-wrap": "wrap-reverse",
    "--layout-wrap-reverse_-_-ms-flex-wrap": "wrap-reverse",
    "--layout-wrap_-_flex-wrap": "wrap",
    "--layout-wrap_-_-webkit-flex-wrap": "wrap",
    "--layout-wrap_-_-ms-flex-wrap": "wrap",
    "--layout-vertical-reverse_-_flex-direction": "column-reverse",
    "--layout-vertical-reverse_-_-webkit-flex-direction": "column-reverse",
    "--layout-vertical-reverse_-_-ms-flex-direction": "column-reverse",
    "--layout-vertical-reverse_-_display": "flex",
    "--layout-vertical_-_flex-direction": "column",
    "--layout-vertical_-_-webkit-flex-direction": "column",
    "--layout-vertical_-_-ms-flex-direction": "column",
    "--layout-vertical_-_display": "flex",
    "--layout-horizontal-reverse_-_flex-direction": "row-reverse",
    "--layout-horizontal-reverse_-_-webkit-flex-direction": "row-reverse",
    "--layout-horizontal-reverse_-_-ms-flex-direction": "row-reverse",
    "--layout-horizontal-reverse_-_display": "flex",
    "--layout-horizontal_-_flex-direction": "row",
    "--layout-horizontal_-_-webkit-flex-direction": "row",
    "--layout-horizontal_-_-ms-flex-direction": "row",
    "--layout-horizontal_-_display": "flex",
    "--layout-inline_-_display": "inline-flex",
    "--layout_-_display": "flex",
    "--material-secondary-text-color": "#727272",
    "--material-secondary-background-color": "#e5e5e5",
    "--material-background-color": "#ffffff",
    "--material-body-text-color": "#212121",
    "--chip-background-color": "rgba(33, 33, 33, 0.15)",
    "--mdc-select-disabled-dropdown-icon-color": "rgba(0, 0, 0, 0.37)",
    "--mdc-select-dropdown-icon-color": "rgba(0, 0, 0, 0.54)",
    "--mdc-select-disabled-ink-color": "rgba(0, 0, 0, 0.37)",
    "--mdc-select-label-ink-color": "rgba(0, 0, 0, 0.6)",
    "--mdc-select-ink-color": "rgba(0, 0, 0, 0.87)",
    "--mdc-select-disabled-fill-color": "rgb(250, 250, 250)",
    "--mdc-select-fill-color": "rgb(245, 245, 245)",
    "--mdc-select-outlined-disabled-border-color": "rgba(0, 0, 0, 0.06)",
    "--mdc-select-outlined-hover-border-color": "rgba(0, 0, 0, 0.87)",
    "--mdc-select-outlined-idle-border-color": "rgba(0, 0, 0, 0.38)",
    "--mdc-select-hover-line-color": "rgba(0, 0, 0, 0.87)",
    "--mdc-select-idle-line-color": "rgba(0, 0, 0, 0.42)",
    "--mdc-text-field-disabled-ink-color": "rgba(0, 0, 0, 0.37)",
    "--mdc-text-field-label-ink-color": "rgba(0, 0, 0, 0.6)",
    "--mdc-text-field-ink-color": "rgba(0, 0, 0, 0.87)",
    "--mdc-text-field-disabled-fill-color": "rgb(250, 250, 250)",
    "--mdc-text-field-fill-color": "rgb(245, 245, 245)",
    "--mdc-text-field-outlined-disabled-border-color": "rgba(0, 0, 0, 0.06)",
    "--mdc-text-field-outlined-hover-border-color": "rgba(0, 0, 0, 0.87)",
    "--mdc-text-field-outlined-idle-border-color": "rgba(0, 0, 0, 0.38)",
    "--mdc-text-field-disabled-line-color": "rgba(0, 0, 0, 0.06)",
    "--mdc-text-field-hover-line-color": "rgba(0, 0, 0, 0.87)",
    "--mdc-text-field-idle-line-color": "rgba(0, 0, 0, 0.42)",
    "--mdc-dialog-content-ink-color": "#212121",
    "--mdc-dialog-heading-ink-color": "#212121",
    "--mdc-dialog-scroll-divider-color": "rgba(0, 0, 0, .12)",
    "--mdc-button-outline-color": "rgba(0, 0, 0, .12)",
    "--mdc-button-disabled-ink-color": "#bdbdbd",
    "--mdc-tab-text-label-color-default": "#212121",
    "--mdc-radio-disabled-color": "#bdbdbd",
    "--mdc-radio-unchecked-color": "rgba(33, 33, 33, 0.54)",
    "--mdc-checkbox-disabled-color": "#bdbdbd",
    "--mdc-checkbox-unchecked-color": "rgba(33, 33, 33, 0.54)",
    "--app-header-background-color": "#03a9f4",
    "--app-header-text-color": "#ffffff",
    "--mdc-theme-error": "#db4437",
    "--mdc-theme-text-icon-on-background": "#727272",
    "--mdc-theme-text-hint-on-background": "#727272",
    "--mdc-theme-text-secondary-on-background": "#727272",
    "--mdc-theme-text-primary-on-background": "#212121",
    "--mdc-theme-text-disabled-on-light": "#bdbdbd",
    "--mdc-theme-on-surface": "#212121",
    "--mdc-theme-on-secondary": "#ffffff",
    "--mdc-theme-on-primary": "#ffffff",
    "--mdc-theme-surface": "#ffffff",
    "--mdc-theme-background": "#fafafa",
    "--mdc-theme-secondary": "#ff9800",
    "--mdc-theme-primary": "#03a9f4",
    "--markdown-code-background-color": "#fafafa",
    "--data-table-background-color": "#ffffff",
    "--paper-slider-container-color": "rgb(194, 194, 194)",
    "--paper-slider-secondary-color": "#b3e5fC",
    "--paper-slider-active-color": "#03a9f4",
    "--paper-slider-pin-start-color": "#03a9f4",
    "--paper-slider-pin-color": "#03a9f4",
    "--paper-slider-knob-start-color": "#03a9f4",
    "--paper-slider-knob-color": "#03a9f4",
    "--table-row-alternative-background-color": "#e5e5e5",
    "--table-row-background-color": "#fafafa",
    "--table-header-background-color": "rgb(245, 245, 245)",
    "--material-shadow-elevation-2dp": "0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 1px 5px 0 rgba(0, 0, 0, 0.12), 0 3px 1px -2px rgba(0, 0, 0, 0.2)",
    "--paper-item-icon-color": "#44739e",
    "--paper-listbox-background-color": "#ffffff",
    "--label-badge-text-color": "rgba(33, 33, 33, 0.8)",
    "--label-badge-background-color": "#ffffff",
    "--slider-track-color": "rgb(194, 194, 194)",
    "--slider-secondary-color": "#b3e5fC",
    "--slider-color": "#03a9f4",
    "--switch-unchecked-track-color": "#000000",
    "--switch-unchecked-button-color": "#fafafa",
    "--switch-checked-track-color": "#03a9f4",
    "--switch-checked-button-color": "#03a9f4",
    "--switch-checked-color": "#03a9f4",
    "--sidebar-icon-color": "rgba(33, 33, 33, 0.6)",
    "--sidebar-selected-icon-color": "#03a9f4",
    "--sidebar-selected-text-color": "#03a9f4",
    "--sidebar-background-color": "#ffffff",
    "--sidebar-text-color": "#212121",
    "--state-unavailable-color": "#bdbdbd",
    "--state-icon-error-color": "#db4437",
    "--shadow-elevation-24dp_-_box-shadow": "0 24px 38px 3px rgba(0, 0, 0, 0.14),\n                    0 9px 46px 8px rgba(0, 0, 0, 0.12),\n                    0 11px 15px -7px rgba(0, 0, 0, 0.4)",
    "--shadow-elevation-16dp_-_box-shadow": "0 16px 24px 2px rgba(0, 0, 0, 0.14),\n                    0  6px 30px 5px rgba(0, 0, 0, 0.12),\n                    0  8px 10px -5px rgba(0, 0, 0, 0.4)",
    "--shadow-elevation-12dp_-_box-shadow": "0 12px 16px 1px rgba(0, 0, 0, 0.14),\n                    0 4px 22px 3px rgba(0, 0, 0, 0.12),\n                    0 6px 7px -4px rgba(0, 0, 0, 0.4)",
    "--shadow-elevation-8dp_-_box-shadow": "0 8px 10px 1px rgba(0, 0, 0, 0.14),\n                    0 3px 14px 2px rgba(0, 0, 0, 0.12),\n                    0 5px 5px -3px rgba(0, 0, 0, 0.4)",
    "--shadow-elevation-6dp_-_box-shadow": "0 6px 10px 0 rgba(0, 0, 0, 0.14),\n                    0 1px 18px 0 rgba(0, 0, 0, 0.12),\n                    0 3px 5px -1px rgba(0, 0, 0, 0.4)",
    "--shadow-elevation-4dp_-_box-shadow": "0 4px 5px 0 rgba(0, 0, 0, 0.14),\n                    0 1px 10px 0 rgba(0, 0, 0, 0.12),\n                    0 2px 4px -1px rgba(0, 0, 0, 0.4)",
    "--shadow-elevation-3dp_-_box-shadow": "0 3px 4px 0 rgba(0, 0, 0, 0.14),\n                    0 1px 8px 0 rgba(0, 0, 0, 0.12),\n                    0 3px 3px -2px rgba(0, 0, 0, 0.4)",
    "--shadow-elevation-2dp_-_box-shadow": "0 2px 2px 0 rgba(0, 0, 0, 0.14),\n                    0 1px 5px 0 rgba(0, 0, 0, 0.12),\n                    0 3px 1px -2px rgba(0, 0, 0, 0.2)",
    "--shadow-none_-_box-shadow": "none",
    "--shadow-transition_-_transition": "box-shadow 0.28s cubic-bezier(0.4, 0, 0.2, 1)",
    "--material-button-font-size": "0.875rem",
    "--material-caption-font-size": "0.75rem",
    "--material-small-font-size": "0.875rem",
    "--material-h6-font-size": "1.25rem",
    "--input-dropdown-icon-color": "rgba(0, 0, 0, 0.54)",
    "--input-disabled-ink-color": "rgba(0, 0, 0, 0.37)",
    "--input-label-ink-color": "rgba(0, 0, 0, 0.6)",
    "--input-ink-color": "rgba(0, 0, 0, 0.87)",
    "--input-disabled-fill-color": "rgb(250, 250, 250)",
    "--input-fill-color": "rgb(245, 245, 245)",
    "--input-outlined-disabled-border-color": "rgba(0, 0, 0, 0.06)",
    "--input-outlined-hover-border-color": "rgba(0, 0, 0, 0.87)",
    "--input-outlined-idle-border-color": "rgba(0, 0, 0, 0.38)",
    "--input-disabled-line-color": "rgba(0, 0, 0, 0.06)",
    "--input-hover-line-color": "rgba(0, 0, 0, 0.87)",
    "--input-idle-line-color": "rgba(0, 0, 0, 0.42)",
    "--history-unknown-color": "#606060",
    "--history-unavailable-color": "transparent",
    "--state-water_heater-performance-color": "#ff6f22",
    "--state-water_heater-high_demand-color": "#ff6f22",
    "--state-water_heater-heat_pump-color": "#ff9800",
    "--state-water_heater-gas-color": "#ff9800",
    "--state-water_heater-electric-color": "#ff9800",
    "--state-water_heater-eco-color": "#4caf50",
    "--state-sensor-battery-medium-color": "#ff9800",
    "--state-sensor-battery-low-color": "#f44336",
    "--state-sensor-battery-high-color": "#4caf50",
    "--state-vacuum-active-color": "#009688",
    "--state-update-active-color": "#ff9800",
    "--state-switch-active-color": "#ffc107",
    "--state-sun-below_horizon-color": "#3f51b5",
    "--state-sun-above_horizon-color": "#ffc107",
    "--state-siren-active-color": "#f44336",
    "--state-plant-active-color": "#f44336",
    "--state-person-home-color": "#4caf50",
    "--state-person-active-color": "#2196f3",
    "--state-media_player-active-color": "#03a9f4",
    "--state-lock-unlocked-color": "#f44336",
    "--state-lock-pending-color": "#ff9800",
    "--state-lock-locked-color": "#4caf50",
    "--state-lock-jammed-color": "#f44336",
    "--state-light-active-color": "#ffc107",
    "--state-lawn_mower-mowing-color": "#009688",
    "--state-lawn_mower-error-color": "#f44336",
    "--state-humidifier-on-color": "#2196f3",
    "--state-fan-active-color": "#00bcd4",
    "--state-device_tracker-home-color": "#4caf50",
    "--state-device_tracker-active-color": "#2196f3",
    "--state-cover-active-color": "#926bc7",
    "--state-climate-heat-cool-color": "#ffc107",
    "--state-climate-heat-color": "#ff6f22",
    "--state-climate-fan_only-color": "#00bcd4",
    "--state-climate-dry-color": "#ff9800",
    "--state-climate-cool-color": "#2196f3",
    "--state-climate-auto-color": "#4caf50",
    "--state-binary_sensor-tamper-on-color": "#f44336",
    "--state-binary_sensor-sound-on-color": "#f44336",
    "--state-binary_sensor-smoke-on-color": "#f44336",
    "--state-binary_sensor-safety-on-color": "#f44336",
    "--state-binary_sensor-problem-on-color": "#f44336",
    "--state-binary_sensor-moisture-on-color": "#f44336",
    "--state-binary_sensor-lock-on-color": "#f44336",
    "--state-binary_sensor-heat-on-color": "#f44336",
    "--state-binary_sensor-gas-on-color": "#f44336",
    "--state-binary_sensor-carbon_monoxide-on-color": "#f44336",
    "--state-binary_sensor-battery-on-color": "#f44336",
    "--state-binary_sensor-active-color": "#ffc107",
    "--state-alert-on-color": "#f44336",
    "--state-alert-off-color": "#ff9800",
    "--state-alarm_control_panel-triggered-color": "#f44336",
    "--state-alarm_control_panel-pending-color": "#ff9800",
    "--state-alarm_control_panel-disarming-color": "#ff9800",
    "--state-alarm_control_panel-arming-color": "#ff9800",
    "--state-alarm_control_panel-armed_vacation-color": "#4caf50",
    "--state-alarm_control_panel-armed_night-color": "#4caf50",
    "--state-alarm_control_panel-armed_home-color": "#4caf50",
    "--state-alarm_control_panel-armed_custom_bypass-color": "#4caf50",
    "--state-alarm_control_panel-armed_away-color": "#4caf50",
    "--state-inactive-color": "#9e9e9e",
    "--state-active-color": "#ffc107",
    "--white-color": "#ffffff",
    "--black-color": "#000000",
    "--blue-grey-color": "#607d8b",
    "--dark-grey-color": "#606060",
    "--grey-color": "#9e9e9e",
    "--light-grey-color": "#bdbdbd",
    "--brown-color": "#795548",
    "--deep-orange-color": "#ff6f22",
    "--orange-color": "#ff9800",
    "--amber-color": "#ffc107",
    "--yellow-color": "#ffeb3b",
    "--lime-color": "#cddc39",
    "--light-green-color": "#8bc34a",
    "--green-color": "#4caf50",
    "--teal-color": "#009688",
    "--cyan-color": "#00bcd4",
    "--light-blue-color": "#03a9f4",
    "--blue-color": "#2196f3",
    "--indigo-color": "#3f51b5",
    "--deep-purple-color": "#6e41ab",
    "--purple-color": "#926bc7",
    "--pink-color": "#e91e63",
    "--red-color": "#f44336",
    "--disabled-color": "#bdbdbd",
    "--rgb-card-background-color": "255, 255, 255",
    "--rgb-text-primary-color": "255, 255, 255",
    "--rgb-secondary-text-color": "114, 114, 114",
    "--rgb-primary-text-color": "33, 33, 33",
    "--rgb-accent-color": "255, 152, 0",
    "--rgb-primary-color": "3, 169, 244",
    "--light-primary-opacity": "1.0",
    "--light-secondary-opacity": "0.7",
    "--light-disabled-opacity": "0.3",
    "--light-divider-opacity": "0.12",
    "--dark-primary-opacity": "0.87",
    "--dark-secondary-opacity": "0.54",
    "--dark-disabled-opacity": "0.38",
    "--dark-divider-opacity": "0.12",
    "--energy-water-color": "#00bcd4",
    "--energy-gas-color": "#8E021B",
    "--energy-battery-in-color": "#f06292",
    "--energy-battery-out-color": "#4db6ac",
    "--energy-non-fossil-color": "#0f9d58",
    "--energy-solar-color": "#ff9800",
    "--energy-grid-return-color": "#8353d1",
    "--energy-grid-consumption-color": "#488fc2",
    "--state-icon-color": "#44739e",
    "--label-badge-grey": "#9e9e9e",
    "--label-badge-yellow": "#ffa600",
    "--label-badge-green": "#43a047",
    "--label-badge-blue": "#039be5",
    "--label-badge-red": "#db4437",
    "--header-height": "56px",
    "--clear-background-color": "#ffffff",
    "--secondary-background-color": "#e5e5e5",
    "--primary-background-color": "#fafafa",
    "--card-background-color": "#ffffff",
    "--info-color": "#039be5",
    "--success-color": "#43a047",
    "--warning-color": "#ffa600",
    "--error-color": "#db4437",
    "--scrollbar-thumb-color": "rgb(194, 194, 194)",
    "--divider-color": "rgba(0, 0, 0, .12)",
    "--accent-color": "#ff9800",
    "--light-primary-color": "#b3e5fC",
    "--dark-primary-color": "#0288d1",
    "--primary-color": "#03a9f4",
    "--disabled-text-color": "#bdbdbd",
    "--text-light-primary-color": "#212121",
    "--text-primary-color": "#ffffff",
    "--secondary-text-color": "#727272",
    "--primary-text-color": "#212121",
    "--material-divider-color": "rgba(0, 0, 0, 0.12)",
    "--material-disabled-color": "rgba(0, 0, 0, 0.26)",
    "--material-error-text-color": "#db4437",
    "--material-error-color": "#db4437",
    "--material-primary-text-color": "#03a9f4",
    "--material-primary-contrast-color": "#fff",
    "--material-primary-color": "#03a9f4",
    "--material-disabled-text-color": "rgba(0, 0, 0, 0.38)",
    "--material-shadow-elevation-24dp": "0 24px 38px 3px rgba(0, 0, 0, 0.14), 0 9px 46px 8px rgba(0, 0, 0, 0.12), 0 11px 15px -7px rgba(0, 0, 0, 0.4)",
    "--material-shadow-elevation-16dp": "0 16px 24px 2px rgba(0, 0, 0, 0.14), 0 6px 30px 5px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.4)",
    "--material-shadow-elevation-12dp": "0 12px 16px 1px rgba(0, 0, 0, 0.14), 0 4px 22px 3px rgba(0, 0, 0, 0.12), 0 6px 7px -4px rgba(0, 0, 0, 0.4)",
    "--material-shadow-elevation-8dp": "0 8px 10px 1px rgba(0, 0, 0, 0.14), 0 3px 14px 2px rgba(0, 0, 0, 0.12), 0 5px 5px -3px rgba(0, 0, 0, 0.4)",
    "--material-shadow-elevation-6dp": "0 6px 10px 0 rgba(0, 0, 0, 0.14), 0 1px 18px 0 rgba(0, 0, 0, 0.12), 0 3px 5px -1px rgba(0, 0, 0, 0.4)",
    "--material-shadow-elevation-4dp": "0 4px 5px 0 rgba(0, 0, 0, 0.14), 0 1px 10px 0 rgba(0, 0, 0, 0.12), 0 2px 4px -1px rgba(0, 0, 0, 0.4)",
    "--material-shadow-elevation-3dp": "0 3px 4px 0 rgba(0, 0, 0, 0.14), 0 1px 8px 0 rgba(0, 0, 0, 0.12), 0 3px 3px -2px rgba(0, 0, 0, 0.4)"
};
